spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: false
#    Do not register with Eureka because this server is eureka itself
    fetch-registry: false

