spring:
  application:
    name: config-server
  profiles:
    active: native
#   native - read from my file system
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888