spring:
  application:
    name: config-server
  profiles:
    active: git
#   native - read from my file system
  cloud:
    config:
      server:
        git:
          uri: https://github.com/semeno4ka/ticketing-project-microservices-config
          default-label: master
          username: semeno4ka
          password: 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
      fail-fast: true

server:
  port: 8888