spring:
  application:
    name: config-server
  profiles:
    active: git
#   native - read from my file system
  cloud:
    config:
      server:
        git:
          uri: https://github.com/semeno4ka/ticketing-project-microservices-config
          default-label: main
#          could be master, depends on the branch name in Git
          username: semeno4ka
#          git doesn't accept regular password, a token must be created
          password: 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
#            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
      fail-fast: true

server:
  port: 8888